### ISSUE TITLE
hello world example

### ISSUE THREAD

**Issue by dominictarr** [nucleus-js/rustyduk#4]
I got this to build, but had trouble 

``` js
// main.js
// Bootstrap the node environment with the dofile builtin.
nucleus.dofile('node_modules/node-core/bootstrap.js')(function (require, module) {
  // node code goes here
});
```

but node-core isn't on npm, it would help if there where some example repos in the org to get started

**Comment by Fishrock123** [comment]
@dominictarr I think that was just an example by @creationix -- I don't think that exists at this time.

**Comment by Fishrock123** [comment]
@dominictarr The `test-app` folders in both this impl and the C-duk impl should work as examples for now... did you have any other trouble?

**Comment by Fishrock123** [comment]
should be fixed by https://github.com/nucleus-js/rustyduk/commit/6ddcc36e420b0852c490118f2dd51d0357588626
